name: e_commerce
description: "A new Flutter project."
publish_to: 'none'

version: 3.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter_paypal_payment: ^1.0.8
  flutter:
    sdk: flutter
#language 
  flutter_localizations:
    sdk: flutter


#Api
  dio: ^5.8.0
  retrofit: ^4.4.0
  json_annotation: ^4.9.0

#Core
  connectivity_plus: ^5.0.2
  flutter_dotenv: ^5.2.1
  flutter_screenutil: ^5.9.3
  flutter_native_splash: ^2.4.1
  get_it: ^8.0.2
  go_router: ^14.3.0
  dartz: ^0.10.1
  device_preview: ^1.2.0

#Firebase
  firebase_auth: ^5.3.2
  firebase_core: ^3.7.0
  firebase_storage: ^12.3.6
  flutter_facebook_auth: ^7.1.1
  cloud_firestore: ^5.4.5
  google_sign_in: ^6.2.2

#supabase
  supabase_flutter: ^2.8.1

#Bloc
  flutter_bloc: ^8.1.6
  flutter_riverpod: ^2.6.1
#shared preferences
  shared_preferences: ^2.3.2
#freezed
  freezed_annotation: ^2.4.1


#UI
  animate_do: ^3.3.2
  fluttertoast: ^8.2.4
  flutter_zoom_drawer: ^3.1.2
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.11
  flutter_svg_provider: ^1.0.6
  flutter_animate: ^4.5.0
  webview_flutter: ^4.7.0
  package_info_plus: ^8.1.1
  carousel_slider: ^5.0.0
  share_plus: ^7.2.2
  badges: ^3.1.2
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.6
  dots_indicator: ^3.0.0
  google_nav_bar: ^5.0.7
  image_picker: ^1.1.2
  line_icons: ^2.0.3
  modal_progress_hud_nsn: ^0.5.1
  skeletonizer: ^1.4.2
  curved_navigation_bar: ^1.0.6
  remixicon: ^1.3.0
  flutter_shimmer: ^2.1.2
  awesome_snackbar_content: ^0.1.5

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  very_good_analysis: ^5.1.0
  flutter_lints: ^3.0.0
  retrofit_generator: '>=8.0.0 <10.0.0' 
  build_runner: ^2.3.3
  json_serializable: ^6.8.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/app_icon.png
    - assets/fonts/
    - .env.dev
    - .env.prod
    - assets/images/vuesax/
    - assets/images/vuesax/outline/home.svg
    - assets/images/vuesax/bold/home.svg
    - assets/images/vuesax/bold/products.svg
    - assets/images/vuesax/bold/shopping-cart.svg
    - assets/images/vuesax/bold/user.svg
    - assets/images/vuesax/outline/products.svg
    - assets/images/vuesax/outline/shopping-cart.svg
    - assets/images/vuesax/outline/user.svg
    - assets/images/customer/avatar.png
  # example:
  fonts:
    - family: 'Cairo'
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
    - family: 'Poppins'
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
flutter_assets:
  assets_path: assets/images
  output_path: lib/core/constants/
  filename: images.dart

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  # image_path: "assets/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icon_app_e_commerce.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  remove_alpha_ios: true
  image_path: "assets/images/icon_app_e_commerce.png"
  adaptive_icon_foreground: "assets/images/icon_app_e_commerce.png"
  adaptive_icon_background: "#ffffff"

flutter_intl:
  enabled: true
